-- ===========================================================================
-- V38 - Distances and travel times the product can actually use
-- ===========================================================================
--
-- The only distance in TMS until now was tms.route.reference_distance_km (V8): a number somebody
-- typed onto a master route. It answers "roughly how long is this corridor" and nothing else.
--
-- It cannot answer the question four different modules are about to ask:
--
--   * planning scoring a proposal on kilometres and duration (JOB 05) needs the distance between
--     *these two stops*, which no master route knows;
--   * a per-km rate component (rates, V30) currently multiplies a figure that may be absent, stale
--     or about a different corridor, and it produces money;
--   * stop sequencing needs an N x N matrix over a shipment's own destinations;
--   * an ETA needs the drive time from where the vehicle is to where it is going, which is not a
--     master-data fact at all.
--
-- So this migration adds the one thing all four share: a cache of measured or estimated legs.
--
-- ---------------------------------------------------------------------------
-- 1. Why a cache table rather than a column somewhere
-- ---------------------------------------------------------------------------
--
-- A leg is not owned by an order, a trip or a route - the same road is driven by all three, and by
-- tomorrow's plan as well. Hanging it off any of them would make the second consumer recompute
-- what the first already paid for, and would tie a fact about the world to the lifecycle of a
-- business record that gets cancelled.
--
-- It is a cache and it is treated as one: rows are disposable, an expired row is simply recomputed,
-- and losing the whole table costs provider calls and no business fact. That is why tms_app is
-- granted DELETE here, exactly as V29 grants it on tms.tracking_position and for the same reason -
-- a table with a retention policy needs the role that runs it to be able to trim it.
--
-- ---------------------------------------------------------------------------
-- 2. Why it is company-scoped
-- ---------------------------------------------------------------------------
--
-- The distance between two points is a fact about the world, not about a tenant, so a global cache
-- would be defensible on the merits and would hit more often.
--
-- It is scoped anyway. The coordinates are not the fact - they are a tenant's master data, and a
-- shared table keyed on them would let one company's warehouse coordinates be inferred from
-- another's cache reads. The cost is computing a shared road once per company; the alternative is
-- explaining a cross-tenant inference channel that exists to save arithmetic. Every other business
-- table in this schema is scoped and this one is not the place to make an exception.
--
-- ---------------------------------------------------------------------------
-- 3. The grid, and why the key is rounded
-- ---------------------------------------------------------------------------
--
-- tms.location stores coordinates at 6 decimal places - about 11 cm. A cache keyed on that never
-- hits: two calls for "the same" warehouse differ in the last digit and each pays for a provider
-- call.
--
-- The key rounds to 4 decimals, about 11 m. That is inside the noise of where a gate actually is
-- and far inside the 30% approximation the local estimator applies, so two points that round
-- together are the same point for this purpose. The stored coordinates keep full precision: the
-- rounding is the *key*, not the answer, so a future provider adapter still receives exactly what
-- the caller asked about.
CREATE TABLE tms.travel_estimate (
    id                  uuid          NOT NULL DEFAULT gen_random_uuid(),
    company_id          uuid          NOT NULL,

    -- What was asked, at full precision.
    origin_latitude       numeric(9,6) NOT NULL,
    origin_longitude      numeric(9,6) NOT NULL,
    destination_latitude  numeric(9,6) NOT NULL,
    destination_longitude numeric(9,6) NOT NULL,

    -- The grid the uniqueness invariant is expressed on. Generated by the database rather than
    -- computed in Java, so two application instances cannot round differently and each keep their
    -- own copy of the same leg.
    origin_key_lat        numeric(9,4) GENERATED ALWAYS AS (round(origin_latitude, 4)) STORED,
    origin_key_lon        numeric(9,4) GENERATED ALWAYS AS (round(origin_longitude, 4)) STORED,
    destination_key_lat   numeric(9,4) GENERATED ALWAYS AS (round(destination_latitude, 4)) STORED,
    destination_key_lon   numeric(9,4) GENERATED ALWAYS AS (round(destination_longitude, 4)) STORED,

    distance_km         numeric(10,3) NOT NULL,
    travel_minutes      integer       NOT NULL,
    -- The algorithm or service that produced it, e.g. LOCAL_GEODESIC_V1. Part of the key: swapping
    -- providers must not silently serve the old one's numbers, and comparing them is how anybody
    -- ever justifies paying for a real router.
    provider            text          NOT NULL,
    -- CACHE is deliberately not storable: a row's source is what produced it, and a row that
    -- claimed to have come from the cache would be describing how it was read, not how it was made.
    source              text          NOT NULL,
    calculated_at       timestamptz   NOT NULL DEFAULT now(),
    expires_at          timestamptz   NOT NULL,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT pk_travel_estimate PRIMARY KEY (id),
    CONSTRAINT fk_travel_estimate_company FOREIGN KEY (company_id)
        REFERENCES tms.company (id) ON DELETE CASCADE,
    CONSTRAINT ck_travel_estimate_distance_nonnegative CHECK (distance_km >= 0),
    CONSTRAINT ck_travel_estimate_minutes_nonnegative CHECK (travel_minutes >= 0),
    CONSTRAINT ck_travel_estimate_provider_not_blank CHECK (btrim(provider) <> ''),
    CONSTRAINT ck_travel_estimate_source CHECK (source IN ('PROVIDER', 'FALLBACK')),
    CONSTRAINT ck_travel_estimate_expiry_after_calculation CHECK (expires_at > calculated_at),
    CONSTRAINT ck_travel_estimate_latitudes CHECK (
        origin_latitude BETWEEN -90 AND 90 AND destination_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_travel_estimate_longitudes CHECK (
        origin_longitude BETWEEN -180 AND 180 AND destination_longitude BETWEEN -180 AND 180)
);

-- One row per (company, leg, provider). ON CONFLICT against this is what makes two instances
-- computing the same leg at the same moment cost one row instead of racing - the same shape
-- V11's assignment index uses, applied to a cache.
--
-- Directional on purpose: A -> B and B -> A are two rows. They are usually the same distance and
-- occasionally not - one-way systems, ferries, restricted turns - and a cache that assumed symmetry
-- would be inventing an answer for a road it was never given.
CREATE UNIQUE INDEX uq_travel_estimate_leg ON tms.travel_estimate (
    company_id, origin_key_lat, origin_key_lon, destination_key_lat, destination_key_lon, provider);

-- The sweep that trims expired rows.
CREATE INDEX ix_travel_estimate_expires_at ON tms.travel_estimate (expires_at);

COMMENT ON TABLE tms.travel_estimate IS
    'Cached road distance and driving time between two points (V38). A cache: rows are disposable, '
    'an expired row is recomputed, and losing the table costs provider calls and no business fact. '
    'Company-scoped because the coordinates are a tenant''s master data even though the distance '
    'between them is not - see the migration header.';

COMMENT ON COLUMN tms.travel_estimate.source IS
    'PROVIDER - a routing service answered. FALLBACK - estimated from the coordinates by '
    'LocalGeodesicRoutingProvider because no provider was available. CACHE is not storable: it '
    'describes how a row was read, not how it was made.';

COMMENT ON COLUMN tms.travel_estimate.origin_key_lat IS
    'The 4-decimal grid (about 11 m) the uniqueness invariant is expressed on. Generated by the '
    'database so two application instances cannot round differently and each keep a copy of the '
    'same leg. The full-precision columns are what a provider adapter is given.';

-- ---------------------------------------------------------------------------
-- 4. Tenant isolation (ADR-005)
-- ---------------------------------------------------------------------------
ALTER TABLE tms.travel_estimate ENABLE ROW LEVEL SECURITY;

-- SELECT, INSERT, UPDATE and DELETE. UPDATE is granted, unlike tms.tracking_position: a cached leg
-- is genuinely refreshed in place when it expires, because the row's identity is the leg and not
-- the measurement. DELETE is granted for the retention sweep, for V29's reason.
GRANT SELECT, INSERT, UPDATE, DELETE ON tms.travel_estimate TO tms_app;

CREATE POLICY p_tenant_company_scope ON tms.travel_estimate
    FOR ALL TO tms_app
    USING (company_id = tms.current_company_id())
    WITH CHECK (company_id = tms.current_company_id());

-- ---------------------------------------------------------------------------
-- Deliberately NOT here
-- ---------------------------------------------------------------------------
--
--   * No vendor adapter, and no columns anticipating one. ADR-007 took the same position for
--     telematics: the port is worth having before the vendor, the vendor is not worth guessing.
--     A real router changes RoutingProviderAdapter and writes a different `provider` value; it
--     needs nothing added here.
--   * No geometry column. The question this table answers is "how far", which is a scalar keyed on
--     two points, not a spatial query. PostGIS earns its place where the question is genuinely
--     spatial - containment, for the geofences of JOB 10 - and adding a geography column here to
--     look modern would cost an index nothing reads.
--   * No route polyline. Drawing the road on a map is a display feature that would multiply this
--     table's size by three orders of magnitude, and nothing in the product asks for it yet.
--   * No traffic or time-of-day dimension. Two speed bands is the least detail that avoids lying
--     about urban round trips; a time-of-day model without a provider behind it would be inventing
--     precision.
