package com.ebim.tms.shared.api;

/**
 * The custom HTTP headers that make up the TMS API contract.
 *
 * <p>They are declared once so that the security filter chain, the controllers, the OpenAPI
 * description and the tests cannot drift apart. See {@code docs/api/API_CONVENTIONS.md}.
 */
public final class ApiHeaders {

    /**
     * Selects the company a request operates in. Required by every company-scoped endpoint,
     * carries the company UUID, and is <em>always</em> validated against the caller's active
     * memberships server-side (ADR-003). It is a selector, never an authorization statement.
     */
    public static final String COMPANY_ID = "X-Company-Id";

    /** Client-supplied trace identifier; generated by the backend when absent, always echoed back. */
    public static final String CORRELATION_ID = "X-Correlation-Id";

    /** Accepted as an alias for {@link #CORRELATION_ID} because most gateways already emit it. */
    public static final String REQUEST_ID = "X-Request-Id";

    /**
     * Optional on the inbound integration API: the sending system's own key for one delivery.
     * Repeating it with the same payload returns the first response instead of executing again;
     * repeating it with a different payload is refused. See
     * {@code docs/integrations/INBOUND_API_V1.md}.
     */
    public static final String IDEMPOTENCY_KEY = "Idempotency-Key";

    /**
     * Set to {@code true} on a response that was replayed from the integration inbox rather than
     * executed, so a partner can see the difference in their own logs.
     */
    public static final String IDEMPOTENT_REPLAY = "X-Idempotent-Replay";

    private ApiHeaders() {}
}
