package com.ebim.tms.masterdata.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.ebim.tms.masterdata.domain.Destination;
import com.ebim.tms.masterdata.domain.DestinationType;
import com.ebim.tms.masterdata.domain.Location;
import com.ebim.tms.masterdata.domain.LocationRole;
import com.ebim.tms.masterdata.domain.LocationType;
import com.ebim.tms.masterdata.domain.Origin;
import com.ebim.tms.masterdata.domain.OriginType;
import com.ebim.tms.masterdata.infrastructure.DestinationRepository;
import com.ebim.tms.masterdata.infrastructure.LocationRepository;
import com.ebim.tms.masterdata.infrastructure.OriginRepository;
import com.ebim.tms.shared.api.ConflictException;
import java.math.BigDecimal;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Answers;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

/**
 * The synchronisation rules of {@link LocationCompatibilityProjector}, proved against mocked
 * repositories so they hold on a machine where Docker - and therefore every Testcontainers
 * suite - is unavailable.
 *
 * <p>What is asserted here is deliberately the set of rules that would fail <em>silently</em>:
 * a projection that is deleted instead of deactivated, a canonical type quietly reclassified by
 * an unrelated legacy edit, an integration-owned external identity overwritten, a code
 * collision accepted. The wiring itself (that the link column really is written, that the
 * database really refuses a cross-company reference) is what the Testcontainers suites cover.
 */
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class LocationCompatibilityProjectorTest {

    private static final UUID COMPANY = UUID.fromString("aaaaaaaa-0000-4000-8000-000000000001");
    private static final UUID ACTOR = UUID.fromString("aaaaaaaa-0000-4000-8000-0000000000e1");
    private static final UUID LOCATION = UUID.fromString("aaaaaaaa-0000-4000-8000-00000000000a");

    @Mock(answer = Answers.RETURNS_DEFAULTS)
    private LocationRepository locationRepository;

    @Mock
    private OriginRepository originRepository;

    @Mock
    private DestinationRepository destinationRepository;

    private LocationCompatibilityProjector projector;

    @BeforeEach
    void setUp() {
        projector = new LocationCompatibilityProjector(locationRepository, originRepository, destinationRepository);
        when(locationRepository.saveAndFlush(any())).thenAnswer(call -> call.getArgument(0));
        when(originRepository.saveAndFlush(any())).thenAnswer(call -> call.getArgument(0));
        when(destinationRepository.saveAndFlush(any())).thenAnswer(call -> call.getArgument(0));
        when(originRepository.save(any())).thenAnswer(call -> call.getArgument(0));
        when(destinationRepository.save(any())).thenAnswer(call -> call.getArgument(0));
    }

    private static Location location(LocationType type, LocationRole... roles) {
        Location location = new Location(COMPANY, "LIM01", "Lima DC", type, "Av. Argentina 1234",
                "Puerta azul", "Callao", "Callao", "Callao", "PE", "America/Lima",
                new BigDecimal("-12.045600"), new BigDecimal("-77.031700"), null, 30, null, null, ACTOR);
        location.replaceRoles(Set.of(roles));
        return location;
    }

    /** {@code Location.id} is generated by Hibernate, so a unit test has to supply it directly. */
    private static Location persisted(Location location) {
        try {
            var field = Location.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(location, LOCATION);
            return location;
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Location.id is no longer a field named 'id'", e);
        }
    }

    private static Origin origin(OriginType type, boolean active) {
        Origin origin = new Origin(COMPANY, "LIM01", "Lima DC", type, "Av. Argentina 1234",
                new BigDecimal("-12.045600"), new BigDecimal("-77.031700"), "America/Lima", null, ACTOR);
        if (!active) {
            origin.deactivate(ACTOR);
        }
        origin.linkToLocation(LOCATION);
        return origin;
    }

    // -----------------------------------------------------------------------
    // Downward: canonical -> legacy
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("a location with the ORIGIN role gets an origin projection carrying its narrowed type")
    void createsTheOriginProjection() {
        Location location = persisted(location(LocationType.DISTRIBUTION_CENTER, LocationRole.ORIGIN));
        when(originRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());
        when(destinationRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());

        projector.synchronize(location, ACTOR);

        ArgumentCaptor<Origin> saved = ArgumentCaptor.forClass(Origin.class);
        verify(originRepository).saveAndFlush(saved.capture());
        assertThat(saved.getValue().code()).isEqualTo("LIM01");
        assertThat(saved.getValue().type()).isEqualTo(OriginType.DISTRIBUTION_CENTER);
        assertThat(saved.getValue().timeZone()).isEqualTo("America/Lima");
        assertThat(saved.getValue().locationId()).isEqualTo(LOCATION);
        verify(destinationRepository, never()).saveAndFlush(any());
    }

    @Test
    @DisplayName("a location with the SHIP_TO role gets a destination projection carrying zone and service time")
    void createsTheDestinationProjection() {
        Location location = persisted(location(LocationType.STORE, LocationRole.SHIP_TO));
        when(originRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());
        when(destinationRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());

        projector.synchronize(location, ACTOR);

        ArgumentCaptor<Destination> saved = ArgumentCaptor.forClass(Destination.class);
        verify(destinationRepository).saveAndFlush(saved.capture());
        assertThat(saved.getValue().type()).isEqualTo(DestinationType.STORE);
        assertThat(saved.getValue().serviceTimeMinutes()).isEqualTo(30);
        assertThat(saved.getValue().district()).isEqualTo("Callao");
        assertThat(saved.getValue().locationId()).isEqualTo(LOCATION);
    }

    @Test
    @DisplayName("dropping the ORIGIN role deactivates the projection instead of deleting it")
    void retiringARoleDeactivatesRatherThanDeletes() {
        Location location = persisted(location(LocationType.STORE, LocationRole.SHIP_TO));
        Origin existing = origin(OriginType.DISTRIBUTION_CENTER, true);
        when(originRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(existing));
        when(destinationRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());

        projector.synchronize(location, ACTOR);

        assertThat(existing.active())
                .as("route, transport_order and planning_run reference this row with ON DELETE "
                        + "RESTRICT, so deleting it would fail rather than tidy up")
                .isFalse();
        // any(Origin.class), not any(): OriginRepository inherits two overloads named delete.
        verify(originRepository, never()).delete(any(Origin.class));
        verify(originRepository, never()).deleteById(any());
    }

    @Test
    @DisplayName("deactivating a location deactivates the projections it still has")
    void deactivationFlowsDownToTheProjections() {
        Location location = persisted(location(LocationType.STORE, LocationRole.SHIP_TO));
        location.deactivate(ACTOR);
        Destination existing = new Destination(COMPANY, "LIM01", "Lima DC", DestinationType.STORE, null, null,
                null, null, null, "PE", null, null, null, 0, null, ACTOR);
        existing.linkToLocation(LOCATION);
        when(originRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.empty());
        when(destinationRepository.findByLocationIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(existing));

        projector.synchronize(location, ACTOR);

        assertThat(existing.active()).isFalse();
    }

    // -----------------------------------------------------------------------
    // Upward: legacy -> canonical
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("an origin with no canonical location adopts a new one holding the ORIGIN role")
    void unlinkedOriginAdoptsALocation() {
        Origin unlinked = new Origin(COMPANY, "PLT01", "Planta Norte", OriginType.PLANT, "Av. Industrial 1",
                null, null, "America/Lima", "EXT-1", ACTOR);
        when(locationRepository.existsByCompanyIdAndExternalSystemAndExternalReference(any(), anyString(), anyString()))
                .thenReturn(false);

        projector.syncFromOrigin(unlinked, ACTOR);

        ArgumentCaptor<Location> saved = ArgumentCaptor.forClass(Location.class);
        verify(locationRepository).saveAndFlush(saved.capture());
        assertThat(saved.getValue().code()).isEqualTo("PLT01");
        assertThat(saved.getValue().type()).isEqualTo(LocationType.PLANT);
        assertThat(saved.getValue().roles()).containsExactly(LocationRole.ORIGIN);
        assertThat(saved.getValue().externalReference()).isEqualTo("EXT-1");
        assertThat(saved.getValue().externalSystem())
                .as("ck_location_external_pair_complete requires a system whenever a reference is present")
                .isEqualTo(LocationCompatibilityProjector.LEGACY_EXTERNAL_SYSTEM);
    }

    @Test
    @DisplayName("renaming an origin onto a code another location holds is refused, not silently dropped")
    void codeCollisionOnTheWayUpIsAConflict() {
        Location location = persisted(location(LocationType.DISTRIBUTION_CENTER, LocationRole.ORIGIN));
        Origin renamed = origin(OriginType.DISTRIBUTION_CENTER, true);
        renamed.applyChanges("TAKEN", "Lima DC", OriginType.DISTRIBUTION_CENTER, null, null, null,
                "America/Lima", null, ACTOR);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));
        when(locationRepository.existsByCompanyIdAndCodeAndIdNot(COMPANY, "TAKEN", LOCATION)).thenReturn(true);

        assertThatThrownBy(() -> projector.syncFromOrigin(renamed, ACTOR))
                .isInstanceOf(ConflictException.class)
                .hasMessageContaining("TAKEN");
    }

    @Test
    @DisplayName("an unrelated origin edit does not reclassify a location the legacy enum cannot express")
    void legacyEditDoesNotReclassifyTheCanonicalType() {
        // STORE narrows to OriginType.OTHER, so an origin reporting OTHER is saying nothing new.
        Location location = persisted(location(LocationType.STORE, LocationRole.ORIGIN, LocationRole.SHIP_TO));
        Origin edited = origin(OriginType.OTHER, true);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromOrigin(edited, ACTOR);

        assertThat(location.type()).isEqualTo(LocationType.STORE);
    }

    @Test
    @DisplayName("a genuinely changed origin type does widen the canonical type")
    void aRealTypeChangeDoesPropagate() {
        Location location = persisted(location(LocationType.STORE, LocationRole.ORIGIN));
        Origin edited = origin(OriginType.PLANT, true);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromOrigin(edited, ACTOR);

        assertThat(location.type()).isEqualTo(LocationType.PLANT);
    }

    @Test
    @DisplayName("a legacy edit never overwrites an external identity a named integration owns")
    void integrationOwnedIdentityIsNotOverwritten() {
        Location location = new Location(COMPANY, "LIM01", "Lima DC", LocationType.DISTRIBUTION_CENTER, null, null,
                null, null, null, "PE", "America/Lima", null, null, null, 0, "EWM", "EWM-77", ACTOR);
        location.replaceRoles(Set.of(LocationRole.ORIGIN));
        persisted(location);
        Origin edited = new Origin(COMPANY, "LIM01", "Lima DC", OriginType.DISTRIBUTION_CENTER, null, null, null,
                "America/Lima", "SOMETHING-ELSE", ACTOR);
        edited.linkToLocation(LOCATION);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromOrigin(edited, ACTOR);

        assertThat(location.externalSystem()).isEqualTo("EWM");
        assertThat(location.externalReference()).isEqualTo("EWM-77");
    }

    @Test
    @DisplayName("an external reference another location already claimed leaves the canonical value alone")
    void aDuplicateLegacyReferenceIsNotClaimed() {
        Location location = persisted(location(LocationType.DISTRIBUTION_CENTER, LocationRole.ORIGIN));
        Origin edited = new Origin(COMPANY, "LIM01", "Lima DC", OriginType.DISTRIBUTION_CENTER, null, null, null,
                "America/Lima", "DUPLICATE", ACTOR);
        edited.linkToLocation(LOCATION);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));
        when(locationRepository.existsByCompanyIdAndExternalSystemAndExternalReferenceAndIdNot(
                eq(COMPANY), anyString(), eq("DUPLICATE"), eq(LOCATION))).thenReturn(true);

        projector.syncFromOrigin(edited, ACTOR);

        assertThat(location.externalReference())
                .as("V6/V7 never constrained external_reference, so a pre-existing duplicate must "
                        + "stay editable rather than become a permanent 409")
                .isNull();
    }

    @Test
    @DisplayName("a destination edit propagates its zone and service time but leaves the time zone it cannot carry")
    void destinationEditLeavesFieldsItCannotCarry() {
        Location location = persisted(location(LocationType.STORE, LocationRole.SHIP_TO));
        UUID zone = UUID.randomUUID();
        Destination edited = new Destination(COMPANY, "LIM01", "Tienda Lima", DestinationType.STORE,
                "Jr. Union 100", null, "Lima", "Lima", "Lima", "PE", null, null, zone, 45, null, ACTOR);
        edited.linkToLocation(LOCATION);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromDestination(edited, ACTOR);

        assertThat(location.zoneId()).isEqualTo(zone);
        assertThat(location.serviceTimeMinutes()).isEqualTo(45);
        assertThat(location.timeZone())
                .as("tms.destination has no time zone column, so a destination edit carries no "
                        + "opinion about it and must not blank it")
                .isEqualTo("America/Lima");
    }

    @Test
    @DisplayName("a destination edit adds the SHIP_TO role to a location that only had ORIGIN")
    void legacyEditAddsTheMissingRole() {
        Location location = persisted(location(LocationType.DISTRIBUTION_CENTER, LocationRole.ORIGIN));
        Destination edited = new Destination(COMPANY, "LIM01", "Lima DC", DestinationType.DISTRIBUTION_CENTER,
                null, null, null, null, null, "PE", null, null, null, 0, null, ACTOR);
        edited.linkToLocation(LOCATION);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromDestination(edited, ACTOR);

        assertThat(location.roles()).containsExactly(LocationRole.ORIGIN, LocationRole.SHIP_TO);
    }

    @Test
    @DisplayName("deactivating an origin deactivates the canonical location it projects")
    void legacyDeactivationFlowsUp() {
        Location location = persisted(location(LocationType.DISTRIBUTION_CENTER, LocationRole.ORIGIN));
        Origin deactivated = origin(OriginType.DISTRIBUTION_CENTER, false);
        when(locationRepository.findByIdAndCompanyId(LOCATION, COMPANY)).thenReturn(Optional.of(location));

        projector.syncFromOrigin(deactivated, ACTOR);

        assertThat(location.active()).isFalse();
    }
}
