package com.ebim.tms.routing.domain;

import com.ebim.tms.shared.reference.GeoPoint;
import com.ebim.tms.shared.reference.RoutingSource;
import com.ebim.tms.shared.reference.TravelEstimate;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

/**
 * One cached leg (migration V38).
 *
 * <p><b>A cache row, not a business record.</b> It has no version column and no audit columns
 * beyond timestamps, because nobody disputes a cache: the row is disposable, an expired one is
 * recomputed, and losing the table costs provider calls and no business fact. Adding optimistic
 * locking would make two instances racing to cache the same road into a conflict, which is the
 * opposite of what should happen - they should both be fine and one row should exist.
 *
 * <p>The grid columns the uniqueness invariant is built on are generated by the database and are
 * deliberately not mapped here: reading them would invite writing them, and the whole point of
 * generating them is that no application instance gets to decide how a coordinate rounds.
 */
@Entity
@Table(name = "travel_estimate")
public class TravelEstimateRow {

    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "company_id", updatable = false, nullable = false)
    private UUID companyId;

    @Column(name = "origin_latitude", updatable = false, nullable = false, precision = 9, scale = 6)
    private BigDecimal originLatitude;

    @Column(name = "origin_longitude", updatable = false, nullable = false, precision = 9, scale = 6)
    private BigDecimal originLongitude;

    @Column(name = "destination_latitude", updatable = false, nullable = false, precision = 9, scale = 6)
    private BigDecimal destinationLatitude;

    @Column(name = "destination_longitude", updatable = false, nullable = false, precision = 9, scale = 6)
    private BigDecimal destinationLongitude;

    @Column(name = "distance_km", nullable = false, precision = 10, scale = 3)
    private BigDecimal distanceKm;

    @Column(name = "travel_minutes", nullable = false)
    private int travelMinutes;

    @Column(name = "provider", nullable = false)
    private String provider;

    @Enumerated(EnumType.STRING)
    @Column(name = "source", nullable = false)
    private RoutingSource source;

    @Column(name = "calculated_at", nullable = false)
    private OffsetDateTime calculatedAt;

    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    protected TravelEstimateRow() {}

    public TravelEstimateRow(UUID companyId, GeoPoint origin, GeoPoint destination, TravelEstimate estimate,
            OffsetDateTime expiresAt) {
        this.companyId = companyId;
        this.originLatitude = origin.latitude();
        this.originLongitude = origin.longitude();
        this.destinationLatitude = destination.latitude();
        this.destinationLongitude = destination.longitude();
        apply(estimate, expiresAt);
    }

    /**
     * Refreshes an expired row in place rather than inserting a second one.
     *
     * <p>The row's identity is the <em>leg</em>, not the measurement: (company, two points,
     * provider) is unique, so a recomputation has nowhere else to go. Keeping the history of what a
     * road used to measure is a question nobody has asked, and answering it here would turn the
     * product's hottest cache into its largest table.
     */
    public void refresh(TravelEstimate estimate, OffsetDateTime expiresAt) {
        apply(estimate, expiresAt);
    }

    private void apply(TravelEstimate estimate, OffsetDateTime expiresAt) {
        this.distanceKm = estimate.distanceKm();
        this.travelMinutes = Math.toIntExact(estimate.travelDuration().toMinutes());
        this.provider = estimate.provider();
        this.source = estimate.source();
        this.calculatedAt = estimate.calculatedAt();
        this.expiresAt = expiresAt;
    }

    /** Whether this row may still be served. Compared against an injected clock's now, never {@code now()}. */
    public boolean isFreshAt(OffsetDateTime moment) {
        return expiresAt.isAfter(moment);
    }

    /**
     * The row as an answer, marked as served from the cache.
     *
     * <p><b>The stored {@code source} is preserved.</b> A straight-line estimate that has been
     * cached is still a straight-line estimate - overwriting its source with "cache" would let
     * storing a figure quietly promote it to a measurement, which is exactly the defect the smoke
     * run caught when the two were one field.
     *
     * <p>{@code calculatedAt} keeps the moment the underlying figure was produced rather than the
     * moment it was read - a consumer asking "how old is this number" wants the former, and the
     * latter is a fact about the read that nobody needs.
     */
    public TravelEstimate toEstimate() {
        return new TravelEstimate(distanceKm, Duration.ofMinutes(travelMinutes), provider, source, true,
                calculatedAt);
    }

    public UUID id() {
        return id;
    }

    public UUID companyId() {
        return companyId;
    }

    public String provider() {
        return provider;
    }

    public OffsetDateTime expiresAt() {
        return expiresAt;
    }

    public GeoPoint origin() {
        return new GeoPoint(originLatitude, originLongitude);
    }

    public GeoPoint destination() {
        return new GeoPoint(destinationLatitude, destinationLongitude);
    }
}
