package com.ebim.tms.shared.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI contract metadata. The contract is owned by the backend, not generated by hand
 * on the frontend side.
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER_SCHEME = "supabaseJwt";

    @Bean
    public OpenAPI tmsOpenApi(TmsApiProperties properties) {
        return new OpenAPI()
                .info(new Info()
                        .title("TMS by EBIM API")
                        .version("v1")
                        .description("""
                                Transport Management System backend API.

                                Every business operation is authenticated with a Supabase-issued JWT and \
                                authorized server-side against the caller's organization/company scope.""")
                        .license(new License().name("Proprietary - EBIM")))
                .components(new Components().addSecuritySchemes(BEARER_SCHEME, new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                        .description("Supabase Auth access token. Base path: " + properties.basePath())));
    }
}
