package com.ebim.tms.shared.config;

import com.ebim.tms.shared.api.ApiHeaders;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI contract metadata. The contract is owned by the backend, not generated by hand on
 * the frontend side.
 *
 * <p>The bearer scheme is declared as a <em>global</em> requirement, so the generated document
 * states that every operation needs a token unless it says otherwise. That matches the filter
 * chain, which is deny-by-default: a contract that implied the opposite would be a
 * documentation bug with security consequences.
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER_SCHEME = "supabaseJwt";

    @Bean
    public OpenAPI tmsOpenApi(TmsApiProperties properties) {
        return new OpenAPI()
                .info(new Info()
                        .title("TMS by EBIM API")
                        .version("v1")
                        .description("""
                                Transport Management System backend API.

                                Every business operation is authenticated with a Supabase-issued JWT and \
                                authorized server-side against the caller's organization/company scope.

                                Company-scoped endpoints require the `%s` header carrying the id of a \
                                company the caller is a member of; the membership is validated on the \
                                server and the header is never trusted on its own. Errors are RFC 9457 \
                                `application/problem+json` documents. See docs/api/API_CONVENTIONS.md."""
                                .formatted(ApiHeaders.COMPANY_ID))
                        .license(new License().name("Proprietary - EBIM")))
                .components(new Components().addSecuritySchemes(BEARER_SCHEME, new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                        .description("Supabase Auth access token. Base path: " + properties.basePath())))
                .addSecurityItem(new SecurityRequirement().addList(BEARER_SCHEME));
    }
}
