import { expect, test, type ConsoleMessage, type Page } from '@playwright/test'
import { signIn, stubServices } from './support/app'

const SHOTS_DIR = 'artifacts/ui-review'

/**
 * Console hygiene and the review screenshots.
 *
 * The screenshots are written to `artifacts/ui-review/`, which is git-ignored: they are a
 * review aid regenerated by `npm run e2e`, not a source artefact to keep under version control.
 */

/** Noise we accept, with the reason. Everything else counts as a console error. */
const ACCEPTED = [
  // Vite injects this when the dev server restarts mid-run; it is tooling, not the product.
  /\[vite\] connecting/i,
  /Download the React DevTools/i,
]

function collectConsoleErrors(page: Page): string[] {
  const errors: string[] = []
  page.on('console', (message: ConsoleMessage) => {
    if (message.type() !== 'error' && message.type() !== 'warning') {
      return
    }
    const text = message.text()
    if (ACCEPTED.some((pattern) => pattern.test(text))) {
      return
    }
    if (message.type() === 'error') {
      errors.push(text)
    }
  })
  page.on('pageerror', (error) => errors.push(`uncaught: ${error.message}`))
  return errors
}

// Both tests walk every screen in the product; the default 30s is not enough for that.
test.describe.configure({ timeout: 120_000 })

const SCREENS = [
  { path: '/', heading: /^Hola,/ },
  { path: '/masters/origins', heading: 'Orígenes' },
  { path: '/masters/destinations', heading: 'Destinos' },
  { path: '/masters/zones', heading: 'Zonas' },
  { path: '/masters/frequencies', heading: 'Frecuencias' },
  { path: '/masters/routes', heading: 'Rutas' },
  { path: '/fleet/carriers', heading: 'Transportistas' },
  { path: '/fleet/vehicle-types', heading: 'Tipos de vehículo' },
  { path: '/fleet/vehicles', heading: 'Vehículos' },
  { path: '/orders', heading: 'Pedidos' },
  { path: '/planning', heading: 'Planificación' },
] as const

test('no console errors while walking every screen', async ({ page }) => {
  const errors = collectConsoleErrors(page)
  await stubServices(page)

  await signIn(page)
  for (const screen of SCREENS) {
    await page.goto(screen.path)
    await expect(page.getByRole('heading', { level: 1, name: screen.heading })).toBeVisible()
  }

  expect(errors, errors.join('\n')).toEqual([])
})

test('captures the review screenshots', async ({ page }) => {
  await stubServices(page)

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/login-desktop.png`, fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/login-mobile.png`, fullPage: true })

  await page.setViewportSize({ width: 1440, height: 900 })
  await signIn(page)
  await expect(page.getByRole('heading', { level: 1, name: /^Hola,/ })).toBeVisible()

  for (const screen of SCREENS) {
    await page.goto(screen.path)
    await expect(page.getByRole('heading', { level: 1, name: screen.heading })).toBeVisible()
    const name = screen.path === '/' ? 'dashboard' : screen.path.replace(/^\//, '').replace(/\//g, '-')
    await page.screenshot({ path: `${SHOTS_DIR}/${name}-desktop.png`, fullPage: true })
  }

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/planning')
  await expect(page.getByRole('heading', { level: 1, name: 'Planificación' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/planning-mobile.png`, fullPage: true })

  await page.goto('/orders')
  await expect(page.getByRole('heading', { level: 1, name: 'Pedidos' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/orders-mobile.png`, fullPage: true })

  await page.getByRole('button', { name: 'Abrir o cerrar la navegación' }).click()
  await expect(page.locator('#tms-sidebar')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/navigation-drawer-mobile.png` })
  await page.keyboard.press('Escape')

  // One form dialog at each end of the range: the fieldset grouping on a wide screen, and the
  // full-screen sheet on a phone.
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/masters/destinations')
  await page.getByRole('button', { name: 'Nuevo destino' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/form-destination-desktop.png` })
  await page.keyboard.press('Escape')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/masters/destinations')
  await page.getByRole('button', { name: 'Nuevo destino' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/form-destination-mobile.png` })
})
