import { expect, test, type ConsoleMessage, type Locator, type Page } from '@playwright/test'
import { signIn, stubServices } from './support/app'
import { stubLocations } from './support/masters'
import { stubPlanning } from './support/planning'

const SHOTS_DIR = 'artifacts/ui-review'

/**
 * Console hygiene and the review screenshots.
 *
 * The screenshots are written to `artifacts/ui-review/`, which is git-ignored: they are a
 * review aid regenerated by `npm run e2e`, not a source artefact to keep under version control.
 */

/** Noise we accept, with the reason. Everything else counts as a console error. */
const ACCEPTED = [
  // Vite injects this when the dev server restarts mid-run; it is tooling, not the product.
  /\[vite\] connecting/i,
  /Download the React DevTools/i,
]

function collectConsoleErrors(page: Page): string[] {
  const errors: string[] = []
  page.on('console', (message: ConsoleMessage) => {
    if (message.type() !== 'error' && message.type() !== 'warning') {
      return
    }
    const text = message.text()
    if (ACCEPTED.some((pattern) => pattern.test(text))) {
      return
    }
    if (message.type() === 'error') {
      errors.push(text)
    }
  })
  page.on('pageerror', (error) => errors.push(`uncaught: ${error.message}`))
  return errors
}

// Both tests walk every screen in the product; the default 30s is not enough for that.
test.describe.configure({ timeout: 120_000 })

const SCREENS = [
  { path: '/', heading: /^Hola,/ },
  { path: '/masters/origins', heading: 'Orígenes' },
  { path: '/masters/destinations', heading: 'Destinos' },
  { path: '/masters/zones', heading: 'Zonas' },
  { path: '/masters/frequencies', heading: 'Frecuencias' },
  { path: '/masters/routes', heading: 'Rutas' },
  { path: '/fleet/carriers', heading: 'Transportistas' },
  { path: '/fleet/vehicle-types', heading: 'Tipos de vehículo' },
  { path: '/fleet/vehicles', heading: 'Vehículos' },
  { path: '/orders', heading: 'Pedidos' },
  { path: '/planning', heading: 'Planificación' },
] as const

test('no console errors while walking every screen', async ({ page }) => {
  const errors = collectConsoleErrors(page)
  await stubServices(page)

  await signIn(page)
  for (const screen of SCREENS) {
    await page.goto(screen.path)
    await expect(page.getByRole('heading', { level: 1, name: screen.heading })).toBeVisible()
  }

  expect(errors, errors.join('\n')).toEqual([])
})

/** Lets a sliding panel finish travelling: a screenshot taken mid-animation shows it half off. */
async function settled(target: Locator): Promise<void> {
  await target.evaluate(async (element) => {
    await Promise.all(element.getAnimations().map((animation) => animation.finished))
  })
}

test('captures the review screenshots', async ({ page }) => {
  await stubServices(page)

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/login-desktop.png`, fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/login-mobile.png`, fullPage: true })

  await page.setViewportSize({ width: 1440, height: 900 })
  await signIn(page)
  await expect(page.getByRole('heading', { level: 1, name: /^Hola,/ })).toBeVisible()

  for (const screen of SCREENS) {
    await page.goto(screen.path)
    await expect(page.getByRole('heading', { level: 1, name: screen.heading })).toBeVisible()
    const name = screen.path === '/' ? 'dashboard' : screen.path.replace(/^\//, '').replace(/\//g, '-')
    await page.screenshot({ path: `${SHOTS_DIR}/${name}-desktop.png`, fullPage: true })
  }

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/planning')
  await expect(page.getByRole('heading', { level: 1, name: 'Planificación' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/planning-mobile.png`, fullPage: true })

  await page.goto('/orders')
  await expect(page.getByRole('heading', { level: 1, name: 'Pedidos' })).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/orders-mobile.png`, fullPage: true })

  await page.getByRole('button', { name: 'Abrir o cerrar la navegación' }).click()
  await expect(page.locator('#tms-sidebar')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/navigation-drawer-mobile.png` })
  await page.keyboard.press('Escape')

  // One form dialog at each end of the range: the fieldset grouping on a wide screen, and the
  // full-screen sheet on a phone.
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/masters/destinations')
  // The page header's button, not the one the empty state also offers: with no rows loaded both
  // are on the screen and a bare getByRole matches two.
  await page.locator('.tms-page-actions').getByRole('button', { name: 'Nuevo destino' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await settled(page.getByRole('dialog'))
  await page.screenshot({ path: `${SHOTS_DIR}/form-destination-desktop.png` })
  await page.keyboard.press('Escape')

  // The carrier form is the one the polish brief used as its worked example of grouping.
  await page.goto('/fleet/carriers')
  await page.getByRole('button', { name: 'Nuevo transportista' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await settled(page.getByRole('dialog'))
  await page.screenshot({ path: `${SHOTS_DIR}/form-carrier-desktop.png` })
  await page.keyboard.press('Escape')

  await page.goto('/fleet/vehicles')
  await page.getByRole('button', { name: 'Nuevo vehículo' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await settled(page.getByRole('dialog'))
  await page.screenshot({ path: `${SHOTS_DIR}/form-vehicle-desktop.png` })
  await page.keyboard.press('Escape')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/masters/destinations')
  // The page header's button, not the one the empty state also offers: with no rows loaded both
  // are on the screen and a bare getByRole matches two.
  await page.locator('.tms-page-actions').getByRole('button', { name: 'Nuevo destino' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await settled(page.getByRole('dialog'))
  await page.screenshot({ path: `${SHOTS_DIR}/form-destination-mobile.png` })
})

/* The list pattern is only judgeable with rows in it: an empty table shows the panel, the
   filter strip and the empty state, but says nothing about density, row rhythm or how the
   count strip and the pager sit against the data. */
test('captures a populated list screen', async ({ page }) => {
  await stubServices(page)
  await stubLocations(page)
  await signIn(page)

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/masters/origins')
  await expect(page.getByText('LIM-CD1')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/masters-origins-populated-desktop.png`, fullPage: true })

  // With the row menu open: the panel is portalled out of the table, so this is also the
  // check that it lands in the right place rather than behind the panel edge.
  await page.getByRole('button', { name: 'Abrir menú de acciones' }).first().click()
  await expect(page.getByRole('menu')).toBeVisible()
  await settled(page.getByRole('menu'))
  await page.screenshot({ path: `${SHOTS_DIR}/masters-origins-row-menu-desktop.png` })
  await page.keyboard.press('Escape')

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByText('LIM-CD1')).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/masters-origins-populated-mobile.png`, fullPage: true })
})

test('captures the planning board with a loaded trip', async ({ page }) => {
  await stubServices(page)
  await stubPlanning(page)
  await signIn(page)

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/planning/run-1')
  await expect(page.getByRole('heading', { level: 1, name: 'PLN-000001' })).toBeVisible()

  // A board with an empty trip proves nothing about the capacity bars, so load one first.
  await page.getByRole('button', { name: 'Nuevo viaje' }).click()
  const dialog = page.getByRole('dialog')
  // `Select` is a button + listbox, not a native `<select>`: open it, then click the option. The
  // listbox is portalled to the document body, so the option is looked up unscoped rather than
  // through `dialog`, and only exists once opened.
  await dialog.getByLabel('Vehículo').click()
  await expect(page.getByRole('option', { name: /VH-001/ })).toBeVisible()
  await page.getByRole('option', { name: /VH-001/ }).click()
  await dialog.getByRole('button', { name: 'Crear viaje' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Asignar' }).first().click()
  await expect(page.getByRole('article').first().getByText('Cerca del límite')).toBeVisible()

  await page.screenshot({ path: `${SHOTS_DIR}/planning-board-desktop.png`, fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Viajes', exact: true }).click()
  await expect(page.getByRole('article').first()).toBeVisible()
  await page.screenshot({ path: `${SHOTS_DIR}/planning-board-mobile.png`, fullPage: true })
})
