package com.ebim.tms.database;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.UUID;
import org.assertj.core.api.ThrowableAssert.ThrowingCallable;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.postgresql.util.PSQLException;

/**
 * What the database itself guarantees about the routing cache (migration V38).
 *
 * <p>The interesting one is the generated grid. The service and the repository both round to four
 * decimals, and if they ever disagreed the cache would look like it worked while quietly never
 * hitting - a defect that costs money in provider calls and shows up as nothing at all. Generating
 * the key in the database is what makes them incapable of disagreeing, and this is where that is
 * proved rather than assumed.
 */
@EnabledIf(value = DockerAvailability.CONDITION, disabledReason = DockerAvailability.DISABLED_REASON)
class RoutingCacheConstraintIntegrationTest {

    private static final String UNIQUE_VIOLATION = "23505";
    private static final String CHECK_VIOLATION = "23514";

    private static String jdbcUrl;
    private Connection connection;

    @BeforeAll
    static void migrate() {
        jdbcUrl = PostgresTestDatabase.createMigratedDatabase("tms_routing_cache");
    }

    @BeforeEach
    void open() throws SQLException {
        connection = PostgresTestDatabase.connect(jdbcUrl);
        connection.setAutoCommit(false);
    }

    @AfterEach
    void rollback() throws SQLException {
        connection.rollback();
        connection.close();
    }

    @Test
    @DisplayName("the grid key is generated by the database, so two coordinates 1 m apart are one leg")
    void theGridCollapsesNeighbouringCoordinates() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);

        // Different at the 6th decimal (about 11 cm), identical at the 4th. The uniqueness index is
        // on the generated grid, so this is the same leg and the insert must be refused.
        assertViolates(UNIQUE_VIOLATION, () -> insertLeg(company,
                "-12.046399", "-77.042751", "-12.052799", "-77.132751", "12.500", 20));

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isEqualTo(1);
    }

    @Test
    @DisplayName("a coordinate 500 m away is a different leg, not a cache hit")
    void theGridDoesNotCollapseGenuinelyDifferentPlaces() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);
        insertLeg(company, "-12.051000", "-77.042793", "-12.052780", "-77.132790", "12.900", 21);

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isEqualTo(2);
    }

    /**
     * A road is not assumed symmetric: one-way systems, ferries and restricted turns all make
     * A to B and B to A genuinely different drives, and a cache that folded them would be inventing
     * an answer for a road it was never given.
     */
    @Test
    @DisplayName("the reverse of a cached leg is a separate row")
    void legsAreDirectional() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);
        insertLeg(company, "-12.052780", "-77.132790", "-12.046374", "-77.042793", "13.100", 22);

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isEqualTo(2);
    }

    @Test
    @DisplayName("the same leg cached against two providers is two rows")
    void providerIsPartOfTheKey() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20,
                "LOCAL_GEODESIC_V1", "FALLBACK");
        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "11.800", 18,
                "VENDOR_X", "PROVIDER");

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isEqualTo(2);
    }

    /**
     * The tenancy line. Two companies caching the same road keep their own rows, which is the cost
     * the migration header accepts in exchange for a tenant's coordinates never appearing in a row
     * another tenant can read.
     */
    @Test
    @DisplayName("the same leg for two companies is two rows, and neither is shared")
    void theCacheIsCompanyScoped() throws SQLException {
        UUID companyA = seedCompany("ROUTE-A");
        UUID companyB = seedCompany("ROUTE-B");

        insertLeg(companyA, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);
        insertLeg(companyB, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isEqualTo(2);
        assertThat(count("SELECT count(*) FROM tms.travel_estimate WHERE company_id = '" + companyA + "'"))
                .isEqualTo(1);
    }

    @Test
    @DisplayName("a cached leg cannot claim to have come from the cache")
    void sourceIsRestricted() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        // CACHE describes how a row was read, not how it was made.
        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20,
                "LOCAL_GEODESIC_V1", "CACHE"));
        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20,
                "LOCAL_GEODESIC_V1", "GUESSED"));
    }

    @Test
    @DisplayName("a negative distance or duration is refused, and so is an expiry before the calculation")
    void figuresAreSane() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-12.046374", "-77.042793", "-12.052780", "-77.132790", "-1.000", 20));
        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", -5));
        assertViolates(CHECK_VIOLATION, () -> execute("INSERT INTO tms.travel_estimate"
                + " (company_id, origin_latitude, origin_longitude, destination_latitude,"
                + " destination_longitude, distance_km, travel_minutes, provider, source,"
                + " calculated_at, expires_at) VALUES ('" + company + "', -12.046374, -77.042793,"
                + " -12.052780, -77.132790, 12.5, 20, 'LOCAL_GEODESIC_V1', 'FALLBACK',"
                + " now(), now() - interval '1 hour')"));
    }

    @Test
    @DisplayName("a coordinate outside the world is refused")
    void coordinatesAreBounded() throws SQLException {
        UUID company = seedCompany("ROUTE-A");

        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-91.000000", "-77.042793", "-12.052780", "-77.132790", "12.500", 20));
        assertViolates(CHECK_VIOLATION, () -> insertLeg(company,
                "-12.046374", "-181.000000", "-12.052780", "-77.132790", "12.500", 20));
    }

    @Test
    @DisplayName("deleting a company takes its cached legs with it")
    void cacheFollowsTheCompany() throws SQLException {
        UUID company = seedCompany("ROUTE-A");
        insertLeg(company, "-12.046374", "-77.042793", "-12.052780", "-77.132790", "12.500", 20);

        execute("DELETE FROM tms.membership WHERE company_id = '" + company + "'");
        execute("DELETE FROM tms.company WHERE id = '" + company + "'");

        assertThat(count("SELECT count(*) FROM tms.travel_estimate")).isZero();
    }

    // --- fixtures --------------------------------------------------------------------

    private UUID seedCompany(String code) throws SQLException {
        UUID organization = insertReturningId("INSERT INTO tms.organization (code, name) VALUES ('ORG-"
                + code + "', 'Org " + code + "') RETURNING id");
        return insertReturningId("INSERT INTO tms.company (organization_id, code, name, time_zone) VALUES ('"
                + organization + "', '" + code + "', 'Company " + code + "', 'America/Lima') RETURNING id");
    }

    private void insertLeg(UUID company, String originLat, String originLon, String destLat, String destLon,
            String distanceKm, int minutes) throws SQLException {
        insertLeg(company, originLat, originLon, destLat, destLon, distanceKm, minutes,
                "LOCAL_GEODESIC_V1", "FALLBACK");
    }

    private void insertLeg(UUID company, String originLat, String originLon, String destLat, String destLon,
            String distanceKm, int minutes, String provider, String source) throws SQLException {
        execute("INSERT INTO tms.travel_estimate (company_id, origin_latitude, origin_longitude,"
                + " destination_latitude, destination_longitude, distance_km, travel_minutes, provider,"
                + " source, expires_at) VALUES ('" + company + "', " + originLat + ", " + originLon + ", "
                + destLat + ", " + destLon + ", " + distanceKm + ", " + minutes + ", '" + provider + "', '"
                + source + "', now() + interval '30 days')");
    }

    private UUID insertReturningId(String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return UUID.fromString(resultSet.getString(1));
        }
    }

    private void execute(String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private long count(String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    /** See {@code TenancyConstraintIntegrationTest} for why a savepoint is used here. */
    private void assertViolates(String sqlState, ThrowingCallable statement) {
        try {
            Savepoint savepoint = connection.setSavepoint();
            try {
                Throwable thrown = catchThrowable(statement);
                assertThat(thrown).as("the database was expected to refuse the statement")
                        .isInstanceOf(PSQLException.class);
                assertThat(((PSQLException) thrown).getSQLState()).isEqualTo(sqlState);
            } finally {
                connection.rollback(savepoint);
            }
        } catch (SQLException failed) {
            throw new IllegalStateException("could not manage the savepoint", failed);
        }
    }
}
